### ISSUE TITLE
Youtube Clipper

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#200]
## Script Title - We have utility for downloading the whole video #159 but now we something to download a small clip from the video based on time

**what will change** - Adding script

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

Happy Coding,

**Comment by vibhorkrishna** [comment]
Can I take this issue?
Till now I have written a script that is able to download the whole video
So I can also complete the issue #159 
Also there have been some changes in hacktoberfest 
Now maintainers need to add "hacktoberfest-accepted" label 
So please do so (link: https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by pawangeek** [comment]
PR should be labelled with hacktober-accepted. Add you can check that in accepted prs, I include that in every accepted one (It should not be random else tagged with spam)

**Comment by pawangeek** [comment]
And go ahead with that, please raise an error if the clip is trying to go beyond the length of video

**Comment by vibhorkrishna** [comment]
hey man I have written a python script and that works on windows but I don't know whether this script will run on linux systems

**Comment by pawangeek** [comment]
That's perfect for now @vibhorkrishna We now backed up with testers, they will review it later

**Comment by vibhorkrishna** [comment]
> PR should be labelled with hacktober-accepted. Add you can check that in accepted prs, I include that in every accepted one (It should not be random else tagged with spam)

Hey man this will be my first ever pull request. I don't know how to label my pull request with hacktober-accepted.
And how do I fill this template??

# Pull Request Template

**script name** - Youtube Clipper

**What have you Changed**
I added the code for youtube clipper

What you changed in the codebase. Write here
I used youtube_dl library for getting the duration of youtube video and getting the download link of the youtube video
I used ffmpeg library to download the video from a starting point to ending point

### Issue no.(must) - #200

### Self Check(Tick After Making pull Request)
I have to fill this after I make a pull request??
Will I be able to do that?
And how to tick??

- [ ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [ ] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

**Comment by pawangeek** [comment]
Vibhor go to pull Hey @vibhorkrishna  just look at how do we create a pull request, you don't need to copy that here

**Comment by vibhorkrishna** [comment]
ok

> PR should be labelled with hacktober-accepted. Add you can check that in accepted prs, I include that in every accepted one (It should not be random else tagged with spam)

But how do I label my pull request with hacktober-accepted??

**Comment by pawangeek** [comment]
I Label that after merging, no need to worry
