### ISSUE TITLE
Fork and Clone Script

### ISSUE THREAD

**Issue by Remakh** [python-geeks/Automation-scripts#319]
## Script Title -

Script that forks a Github repository to your account and clones it to your device. Hacktoberfest inspired.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Remakh** [comment]
assign me please

**Comment by m4dummies** [comment]
Can you assign this to me please?

**Comment by Sacrezar** [comment]
I am sorry @m4dummies but since it is the first time for @Remakh, I'll let him try

@Remakh It would be cool if you let the user choose between a default directory (hardcoded why not) or a given directory when launching the script. 

Also, if it's possible for you to choose where to fork the given repo (like I don't want it on my profile but on my association), could you try this please?

**Comment by Remakh** [comment]
Sure I'll give that a shoot. I've already got something done, I'll add those suggested changes in. 
When you say association, I assume you're talking about forking to your organization? That's what it's referred to on the Github API.

**Comment by Sacrezar** [comment]
Yes organization is the right name, my bad

**Comment by m4dummies** [comment]
All the best @Remakh
